---
title: "DSS Challenge 1"
author: "Alexandra B-K"
date: "7/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.width=8, fig.height=6, fig.path='Figs/', echo=TRUE, tidy=TRUE, message=F, warning=F, cache=T)
```

# Load Required Packages
```{r}
library(Amelia)
library(ggplot2)
library(tidyr)
library(dplyr)
library(ggthemes)
library(ggpubr)
library(FSA)
library(ggcorrplot)

```


# Load Data, Basic Info 
```{r}
edu <- read.csv("/Users/basilaka/Desktop/dss/ed_kaggle.csv", na.strings=c("")) #fill in NA where black but clearly missing data 
edu <- subset(edu, select=-Comments) #removed "Comments" for now


#observations: 8625 - lots of missing data 
#after removing outliers: 8297
#after removing NA from department and overall pay: 2477
```

# Remove extraneous things ($, commas, etc)
```{r}

edu$Overall.Pay <- gsub("\\$", "", edu$Overall.Pay)
edu$Overall.Pay <- gsub(',','',edu$Overall.Pay)
edu$Overall.Pay <- gsub('-','',edu$Overall.Pay) #assuming negative pay is an error... 
edu$Program.Year <- gsub('st','',edu$Program.Year)
edu$Program.Year <- gsub('nd','',edu$Program.Year)
edu$Program.Year <- gsub('rd','',edu$Program.Year)
edu$Program.Year <- gsub('th','',edu$Program.Year)


str(edu)
edu$Overall.Pay <- as.numeric(edu$Overall.Pay)  
summary(edu)

fig1 <- ggplot(edu, aes(x=Program.Year, y=Overall.Pay)) + geom_boxplot() # look at the outliers! 
fig1 

#remove those outliers
boxplot(edu$Overall.Pay)
boxplot(edu$Overall.Pay)$out
boxplot(edu$Overall.Pay, plot=FALSE)$out
outliers <- boxplot(edu$Overall.Pay, plot=FALSE)$out
#print(outliers)
#outli <- edu[which(edu$Overall.Pay %in% outliers),]
edu <- edu[-which(edu$Overall.Pay %in% outliers),] #yields 8297 remaining 
boxplot(edu$Overall.Pay)
print(ggplot(edu, aes(x=Program.Year, y=Overall.Pay)) + geom_boxplot())

```


# Visualize NAs
```{r}
missmap(edu,col=c("yellow","black"))

#then filter NA from Department and Overall Pay (variables of interest)
edu <- edu %>% drop_na(Department, Overall.Pay)

```

# Remove nonwords 
```{r}
library("qdapRegex")
rm_non_words(edu$Department, trim = TRUE, clean = TRUE,
  pattern = "@rm_non_words", replacement = " ", extract = FALSE,
  dictionary = getOption("regex.library"))


```


# Visualise most common departments 
```{r}
library(wordcloud)
library(RColorBrewer)
library(wordcloud2)
library(tm)
text <- edu$Department 
docs <- Corpus(VectorSource(text)) 
docs <- tm_map(docs, removePunctuation)
docs <- tm_map(docs, stemDocument) #stemmed text to remove plurals as separate cases (eg., sciences & science are the same)
docs <- tm_map(docs, removeWords, stopwords("english")) #remove words like 'and' 
docs <- tm_map(docs, content_transformer(tolower))

dtm <- TermDocumentMatrix(docs) 
matrix <- as.matrix(dtm) 
words <- sort(rowSums(matrix),decreasing=TRUE) 
df <- data.frame(word = names(words),freq=words)
set.seed(1234) # for reproducibility 
wordcloud(words = df$word, freq = df$freq, min.freq = 1,max.words=200, random.order=FALSE, rot.per=0.35,colors=brewer.pal(8, "Dark2"))

##another visualization 

barplot(df[1:10,]$freq, las = 2, names.arg = df[1:10,]$word, col ="lightblue", main ="Most frequent words", ylab = "Word frequencies")

#findAssocs(dtm, terms = "science", corlimit = 0.3)
#for purposes of time, hoping to stick with the top 10 words to create dept. categories. 

```


# Filter anything that doesn't have one of the top departments in it 
```{r}
#not including science since captured in things like "political science" and biology is a science 
#yields 1740 observations 

edu <- as.data.frame(edu)

edu$top_ten_depts <- grepl('Biology|Comput|Engineer|Biomed|English|Physic|Molecular|Materi',edu$Department) #T/F return for any dept that is not in top 10 

edu.filt <- subset(edu,top_ten_depts=="TRUE")


```

# Assign to groups 
```{r}
#edu.filt <- edu.filt %>% drop_na(University, Department)
library(stringr)

dept.label <- function(deptartment){
  out <- deptartment
  for(i in 1:length(deptartment)) {
    if(str_detect(deptartment[i],"Biology")) {
      out[i] <- "Biology"
    } else if(str_detect(deptartment[i],"Comput")) {
      out[i] <- "Computing"
    } else if(str_detect(deptartment[i],"Biomed")) {
      out[i] <- "Biomedical"
    } else if(str_detect(deptartment[i],"English")) {
      out[i] <- "English" 
    } else if(str_detect(deptartment[i],"Physic")) {
      out[i] <- "Physics"
    } else if(str_detect(deptartment[i],"Molecular")) {
      out[i] <- "Molecular"
    } else if(str_detect(deptartment[i],"Materi")) {
      out[i] <- "Materials Science" 
    } else {
      out[i] <- "Other" 
    }
  }
  return(out)
}

edu.filt$label <- dept.label(edu.filt$Department)

```


# Visualize pay across to departments / other plots 
```{r}

edu.filt$Overall.Pay <- gsub("\\$", "", edu.filt$Overall.Pay)
edu.filt$Overall.Pay <- gsub(',','',edu.filt$Overall.Pay)
edu.filt$Overall.Pay <- as.numeric(edu.filt$Overall.Pay)

pay.by.dept <- ggplot(edu.filt, aes(x=label, y=Overall.Pay)) + geom_boxplot(aes(fill=factor(label))) + theme_bw() + ggtitle("Overall Pay by Department") +xlab("Area of Study") + ylab("Overall Pay")
print(pay.by.dept)

pay.by.yr <- ggplot(edu.filt, aes(x=Program.Year, y=Overall.Pay)) + geom_boxplot(aes(fill=factor(Program.Year))) + theme_bw() + ggtitle("Overall Pay by Academic Year") + xlab("Program Year") + ylab("Overall Pay")
print(pay.by.yr)

edu.filt.four.year <- filter(edu.filt, Program.Year <= 4) #1669 observations 

pay.by.4yr <- ggplot(edu.filt.four.year, aes(x=Program.Year, y=Overall.Pay)) + geom_boxplot(aes(fill=factor(Program.Year))) + facet_wrap(vars(label)) + theme_bw() + ggtitle("Overall Pay: First 4 AYs") + xlab("Program Year") + ylab("Overall Pay")
print(pay.by.4yr)
```

# ANOVA 
```{r}
group_by(edu.filt.four.year, label) %>%
  summarise(
    count = n(),
    mean = mean(Overall.Pay, na.rm = TRUE),
    sd = sd(Overall.Pay, na.rm = TRUE))

ggline(edu.filt.four.year, x = "label", y = "Overall.Pay", 
       add = c("mean_se", "jitter"), 
       order = c("Biology", "Biomedical", "Computing","English","Materials Science", "Molecular",   "Physics", "Other"),
       ylab = "Overall Pay", xlab = "Department")

# Compute ANOVA
res.aov <- aov(Overall.Pay ~ label, data = edu.filt.four.year)
summary(res.aov)
plot(res.aov, 1)
plot(res.aov,2) # outliers, may affect HOV 
TukeyHSD(res.aov) 
aov_residuals <- residuals(object = res.aov )
shapiro.test(x = aov_residuals) # data set violates normality 

kw.by.yr <- kruskal.test(Overall.Pay ~ label, data = edu.filt.four.year) #cause some of the ANOVA assumptions violated 
DT <- dunnTest(Overall.Pay ~ label, data = edu.filt.four.year, method="bh")  
print(DT)

```

# Explore LW / Predict Pay from LW Ratio? 
```{r}
library(caTools)

edu.filt.four.year <- filter(edu.filt.four.year, LW.Ratio>=0) # remove negative values 

correlate <- cor(edu.filt.four.year$Overall.Pay, edu.filt.four.year$LW.Ratio, use="na.or.complete") 

scatter <- ggplot(edu.filt.four.year, aes(x=LW.Ratio, y=Overall.Pay, color=factor(label))) + 
geom_point() + geom_jitter() + facet_grid(.~ label) + xlab("LW Ratio") + ylab("Overall Pay") + ggtitle("Relationship Between Overall Pay and LW Ratio by Department") + theme_bw() + theme(axis.text.x = element_text(angle = 90), strip.text = element_text(face="bold", size=5.5))

print(scatter)

scatter2 <- ggplot(edu.filt.four.year, aes(x=LW.Ratio, y=Overall.Pay, color=factor(label))) + 
geom_point() + geom_jitter() + facet_grid(label ~ Program.Year) + xlab("LW Ratio by Program Year") + ylab("Overall Pay") + ggtitle("Relationship Between Overall Pay and LW Ratio by Department") + theme_bw() + theme(axis.text.x = element_text(angle = 90), strip.text = element_text(face="bold", size=5.5))

print(scatter2)

#not yet splitting by test/train 
# trialmod <- lm(Overall.Pay ~ LW.Ratio + factor(label), data=edu.filt.four.year)
# summary(trialmod)

#train prediction model 
set.seed(123)
split <- sample.split(edu.filt.four.year$Overall.Pay, SplitRatio = .70)
train <- subset(edu.filt.four.year, split==T) 
test <- subset(edu.filt.four.year, split==F) 

model.pay <- lm(Overall.Pay ~ LW.Ratio, data=train)
summary(model.pay)

test.pay <- predict(model.pay, test)
summary(test.pay)

#plot model 

model.plot <- ggplot() +
  geom_point(aes(x=test$LW.Ratio, y=test$Overall.Pay), color='red') +
  geom_line(aes(x=train$LW.Ratio, y=predict(model.pay, train)), color='blue') +
  ggtitle("Pay vs. LW Ratio") +
  xlab("LW Ratio") +
  ylab("Overall Pay")

model.plot

  



```


# Resources
```{r}
# http://www.sthda.com/english/wiki/text-mining-and-word-cloud-fundamentals-in-r-5-simple-steps-you-should-know
# https://towardsdatascience.com/create-a-word-cloud-with-r-bde3e7422e8a
# https://amunategui.github.io/stringdist/
#https://medium.com/my-datascience-journal/using-string-distance-to-group-text-variables-in-r-aa6d0f9226a6
```

